### ISSUE TITLE
[v1.0.1-7.1] Copper cables (possibly other cables) become disconnected upon world reload.

### ISSUE THREAD

**Issue by Chloroxite** [bta-team-port/industry#18]
Whenever you exit a world, the next time it is loaded up it appears that any cables attached to a machine become functionally (but not visually) disconnected from the machines, and stop transmitting power to said machines. If this happens it requires the cables to be picked up and placed back down to fix.

**Comment by DaCookieCakes** [comment]
Turns out this was a Catalyst issue, and has been patched.
